### ISSUE TITLE
Why ^G to abort readstr? I would have guessed ^C

### ISSUE THREAD

**Issue by bjornbm** [philanc/ple#13]
Basically what the title says. My experience is that ^C is the “cancellation” keystroke (for example, at all shell prompts I've used).

Maybe there is precedence for using ^G to cancel/abort this that I am unaware of?

**Comment by philanc** [comment]
^G is the key to cancel a command in Emacs.

IIRC, in Emacs, ^C is defined as a prefix, used for mode-specific commands.

**Comment by bjornbm** [comment]
Interesting!

I have been meaning to ask about the philosophy with respect to emacs editing key. I use emacs-like commands in a lot of other situations (any macOS text field, shells, readline…) but have used emacs itself very little (as you can tell from this question).

For example, ^O, ^K, ^J behave differently in ple than in macOS text fields and the stock emacs I just installed to test keybindings. I can rebind these to my liking in my ple_init, of course, but have been wondering about where the default ple bindings come from.

**Comment by philanc** [comment]
> about the philosophy with respect to emacs editing key

I have been loosely inspired by emacs (that I used a lot many years ago).  On the other hand since day 1 I wanted 'ple' to be as simple as possible, and also usable on most terminals and terminal emulators, and over telnet or ssh.

I eliminated ESC-key sequences because lots of Ascii sequences returned by special keys (arrows, function keys, ...) start with ESC and it makes parsing them more complex.

Regarding special keys, I want ple to be usable without them (it was the initial emacs philosophy). I also don't want to support sequences which are not supported or are not the same in every terminal emulator. This eliminated common key-combos such as ctrl-<arrows> or shift-<arrows>.

So for example for move-word-backward, often mapped to ctrl-rightarrow. I had to either not to use it, or map it to some available, easy to type keys.  I selected ^J which was redundant with ^M / Return.  Then for move-word-backward, I decided to use ^K which is just on the right of ^J. Then I changed ^W so that without a selection, it kills the current line (which I use more often than the original ^K / Kill-to-end-of-line.  And so on...

Again, ple is *NOT* an emacs-wannabe clone.  Just a *very simple* editor.

**Comment by bjornbm** [comment]
Thanks for the clarifications!

> Again, ple is *NOT* an emacs-wannabe clone. Just a *very simple* editor.

Indeed. I am not looking for an emacs clone. :)

I appreciate the *very simple* approach, and the portability. And respect that you will and should reject any suggestions or pull requests that would be counter to the philosophy! (Touched on also in #12.)

(I may suggest some changes just to test the waters, when I am not sure if something is the way it is deliberately or by “accident”. But don't feel obliged to accept just because I put in the effort – it is done with full knowledge that you may not want it.)
